from common.core.exceptions import SException


class PasswordValidationError(SException):
    pass
